x-rails: &base-rails
  build: .
  volumes:
    - .:/var/www/app:cached
  depends_on:
    - postgres

services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  rails:
    <<: *base-rails
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
  rails_test:
    <<: *base-rails
    command: bundle exec guard --no-bundler-warning --no-interactions
    environment:
      RAILS_ENV: test


